name: Your Workflow Name

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: owner/repo
          ref: ${{ github.ref }}
        env:
          CI: true

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Start SonarQube container
        run: |
          docker run -d --name sonarqube -p 9000:9000 sonarqube:latest

      - name: Build with Maven
        run: mvn clean package

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://e2da-110-226-178-161.ngrok-free.app/
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}

      - name: Stop SonarQube container
        run: docker stop sonarqube
